######################################################################
# Automatically generated by qmake (3.1) Sat May 10 21:24:23 2025
######################################################################

TEMPLATE = app
TARGET = dfm_pattern_match
CONFIG += c++14

# Qt modules
QT += widgets core gui

# For gdstk and its dependencies (Clipper, Qhull)
INCLUDEPATH += . \
               gBolt/include \
               gBolt/extern/jemalloc \
               gBolt/extern/jemalloc/include \
               /home/amrmuhammad/dev/gdstk/include \
               /usr/include # For zlib, qhull if system-installed

# Adjust if your Clipper/Qhull headers are elsewhere, though gdstk usually includes them or they are standard.

LIBS += /home/amrmuhammad/dev/gdstk/build/src/libgdstk.a \
        /home/amrmuhammad/dev/gdstk/build/external/libclipper.a \
        -L/usr/local/lib -lqhull_r \
        -lz # For zlib

# Original INCLUDEPATH (retained for now, qmake might handle Qt paths better)
# INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += layoutwidget.h \
           gBolt/include/common.h \
           gBolt/include/config.h \
           gBolt/include/database.h \
           gBolt/include/gbolt.h \
           gBolt/include/graph.h \
           gBolt/include/history.h \
           gBolt/include/output.h \
           gBolt/include/path.h \
           gBolt/extern/cxxopts/include/cxxopts.hpp \
           gBolt/extern/cxxopts/test/catch.hpp \
           gBolt/extern/jemalloc/include/msvc_compat/strings.h \
           gBolt/extern/jemalloc/include/msvc_compat/windows_extra.h \
           gBolt/extern/jemalloc/msvc/test_threads/test_threads.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/arena_externs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/arena_inlines_a.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/arena_inlines_b.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/arena_stats.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/arena_structs_a.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/arena_structs_b.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/arena_types.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/assert.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/atomic.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/atomic_c11.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/atomic_gcc_atomic.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/atomic_gcc_sync.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/atomic_msvc.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/background_thread_externs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/background_thread_inlines.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/background_thread_structs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/base_externs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/base_inlines.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/base_structs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/base_types.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/bin.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/bin_stats.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/bin_types.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/bit_util.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/bitmap.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/cache_bin.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/ckh.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/ctl.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/div.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/emitter.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/extent_dss.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/extent_externs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/extent_inlines.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/extent_mmap.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/extent_structs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/extent_types.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/hash.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/hook.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/jemalloc_internal_decls.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/jemalloc_internal_externs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/jemalloc_internal_includes.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_a.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_b.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/jemalloc_internal_macros.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/jemalloc_internal_types.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/large_externs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/log.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/malloc_io.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/mutex.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/mutex_pool.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/mutex_prof.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/nstime.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/pages.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/ph.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/prng.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/prof_externs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/prof_inlines_a.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/prof_inlines_b.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/prof_structs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/prof_types.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/ql.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/qr.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/quantum.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/rb.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/rtree.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/rtree_tsd.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/sc.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/seq.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/smoothstep.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/spin.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/stats.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/sz.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/tcache_externs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/tcache_inlines.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/tcache_structs.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/tcache_types.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/test_hooks.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/ticker.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/tsd.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/tsd_generic.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/tsd_malloc_thread_cleanup.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/tsd_tls.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/tsd_types.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/tsd_win.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/util.h \
           gBolt/extern/jemalloc/include/jemalloc/internal/witness.h \
           gBolt/extern/jemalloc/include/msvc_compat/C99/stdbool.h \
           gBolt/extern/jemalloc/include/msvc_compat/C99/stdint.h \
           gBolt/extern/jemalloc/test/include/test/btalloc.h \
           gBolt/extern/jemalloc/test/include/test/extent_hooks.h \
           gBolt/extern/jemalloc/test/include/test/math.h \
           gBolt/extern/jemalloc/test/include/test/mq.h \
           gBolt/extern/jemalloc/test/include/test/mtx.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-alti.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params11213.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params1279.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params132049.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params19937.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params216091.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params2281.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params4253.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params44497.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params607.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-params86243.h \
           gBolt/extern/jemalloc/test/include/test/SFMT-sse2.h \
           gBolt/extern/jemalloc/test/include/test/SFMT.h \
           gBolt/extern/jemalloc/test/include/test/test.h \
           gBolt/extern/jemalloc/test/include/test/thd.h \
           gBolt/extern/jemalloc/test/include/test/timer.h
SOURCES += layoutwidget.cpp \
           design_layout_viewer.cpp \
           dfm_hierarchy_construction.cpp \
           dfm_pattern_capture.cpp \
           gBolt/src/database.cc \
           gBolt/src/gbolt.cc \
           gBolt/src/gbolt_count.cc \
           gBolt/src/gbolt_execute.cc \
           gBolt/src/gbolt_extend.cc \
           gBolt/src/gbolt_mine.cc \
           gBolt/src/history.cc \
           gBolt/src/output.cc \
           gBolt/extern/jemalloc/src/arena.c \
           gBolt/extern/jemalloc/src/background_thread.c \
           gBolt/extern/jemalloc/src/base.c \
           gBolt/extern/jemalloc/src/bin.c \
           gBolt/extern/jemalloc/src/bitmap.c \
           gBolt/extern/jemalloc/src/ckh.c \
           gBolt/extern/jemalloc/src/ctl.c \
           gBolt/extern/jemalloc/src/div.c \
           gBolt/extern/jemalloc/src/extent.c \
           gBolt/extern/jemalloc/src/extent_dss.c \
           gBolt/extern/jemalloc/src/extent_mmap.c \
           gBolt/extern/jemalloc/src/hash.c \
           gBolt/extern/jemalloc/src/hook.c \
           gBolt/extern/jemalloc/src/jemalloc.c \
           gBolt/extern/jemalloc/src/jemalloc_cpp.cpp \
           gBolt/extern/jemalloc/src/large.c \
           gBolt/extern/jemalloc/src/log.c \
           gBolt/extern/jemalloc/src/malloc_io.c \
           gBolt/extern/jemalloc/src/mutex.c \
           gBolt/extern/jemalloc/src/mutex_pool.c \
           gBolt/extern/jemalloc/src/nstime.c \
           gBolt/extern/jemalloc/src/pages.c \
           gBolt/extern/jemalloc/src/prng.c \
           gBolt/extern/jemalloc/src/prof.c \
           gBolt/extern/jemalloc/src/rtree.c \
           gBolt/extern/jemalloc/src/sc.c \
           gBolt/extern/jemalloc/src/stats.c \
           gBolt/extern/jemalloc/src/sz.c \
           gBolt/extern/jemalloc/src/tcache.c \
           gBolt/extern/jemalloc/src/test_hooks.c \
           gBolt/extern/jemalloc/src/ticker.c \
           gBolt/extern/jemalloc/src/tsd.c \
           gBolt/extern/jemalloc/src/witness.c \
           gBolt/extern/jemalloc/src/zone.c \
           gBolt/build/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
           gBolt/build/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           gBolt/extern/jemalloc/msvc/test_threads/test_threads.cpp \
           gBolt/extern/jemalloc/msvc/test_threads/test_threads_main.cpp \
           gBolt/extern/jemalloc/test/integration/aligned_alloc.c \
           gBolt/extern/jemalloc/test/integration/allocated.c \
           gBolt/extern/jemalloc/test/integration/extent.c \
           gBolt/extern/jemalloc/test/integration/malloc.c \
           gBolt/extern/jemalloc/test/integration/mallocx.c \
           gBolt/extern/jemalloc/test/integration/MALLOCX_ARENA.c \
           gBolt/extern/jemalloc/test/integration/overflow.c \
           gBolt/extern/jemalloc/test/integration/posix_memalign.c \
           gBolt/extern/jemalloc/test/integration/rallocx.c \
           gBolt/extern/jemalloc/test/integration/sdallocx.c \
           gBolt/extern/jemalloc/test/integration/slab_sizes.c \
           gBolt/extern/jemalloc/test/integration/smallocx.c \
           gBolt/extern/jemalloc/test/integration/thread_arena.c \
           gBolt/extern/jemalloc/test/integration/thread_tcache_enabled.c \
           gBolt/extern/jemalloc/test/integration/xallocx.c \
           gBolt/extern/jemalloc/test/src/btalloc.c \
           gBolt/extern/jemalloc/test/src/btalloc_0.c \
           gBolt/extern/jemalloc/test/src/btalloc_1.c \
           gBolt/extern/jemalloc/test/src/math.c \
           gBolt/extern/jemalloc/test/src/mq.c \
           gBolt/extern/jemalloc/test/src/mtx.c \
           gBolt/extern/jemalloc/test/src/SFMT.c \
           gBolt/extern/jemalloc/test/src/test.c \
           gBolt/extern/jemalloc/test/src/thd.c \
           gBolt/extern/jemalloc/test/src/timer.c \
           gBolt/extern/jemalloc/test/stress/hookbench.c \
           gBolt/extern/jemalloc/test/stress/microbench.c \
           gBolt/extern/jemalloc/test/unit/a0.c \
           gBolt/extern/jemalloc/test/unit/arena_reset.c \
           gBolt/extern/jemalloc/test/unit/arena_reset_prof.c \
           gBolt/extern/jemalloc/test/unit/atomic.c \
           gBolt/extern/jemalloc/test/unit/background_thread.c \
           gBolt/extern/jemalloc/test/unit/background_thread_enable.c \
           gBolt/extern/jemalloc/test/unit/base.c \
           gBolt/extern/jemalloc/test/unit/binshard.c \
           gBolt/extern/jemalloc/test/unit/bit_util.c \
           gBolt/extern/jemalloc/test/unit/bitmap.c \
           gBolt/extern/jemalloc/test/unit/ckh.c \
           gBolt/extern/jemalloc/test/unit/decay.c \
           gBolt/extern/jemalloc/test/unit/div.c \
           gBolt/extern/jemalloc/test/unit/emitter.c \
           gBolt/extern/jemalloc/test/unit/extent_quantize.c \
           gBolt/extern/jemalloc/test/unit/fork.c \
           gBolt/extern/jemalloc/test/unit/hash.c \
           gBolt/extern/jemalloc/test/unit/hook.c \
           gBolt/extern/jemalloc/test/unit/huge.c \
           gBolt/extern/jemalloc/test/unit/junk.c \
           gBolt/extern/jemalloc/test/unit/junk_alloc.c \
           gBolt/extern/jemalloc/test/unit/junk_free.c \
           gBolt/extern/jemalloc/test/unit/log.c \
           gBolt/extern/jemalloc/test/unit/mallctl.c \
           gBolt/extern/jemalloc/test/unit/malloc_io.c \
           gBolt/extern/jemalloc/test/unit/math.c \
           gBolt/extern/jemalloc/test/unit/mq.c \
           gBolt/extern/jemalloc/test/unit/mtx.c \
           gBolt/extern/jemalloc/test/unit/nstime.c \
           gBolt/extern/jemalloc/test/unit/pack.c \
           gBolt/extern/jemalloc/test/unit/pages.c \
           gBolt/extern/jemalloc/test/unit/ph.c \
           gBolt/extern/jemalloc/test/unit/prng.c \
           gBolt/extern/jemalloc/test/unit/prof_accum.c \
           gBolt/extern/jemalloc/test/unit/prof_active.c \
           gBolt/extern/jemalloc/test/unit/prof_gdump.c \
           gBolt/extern/jemalloc/test/unit/prof_idump.c \
           gBolt/extern/jemalloc/test/unit/prof_log.c \
           gBolt/extern/jemalloc/test/unit/prof_reset.c \
           gBolt/extern/jemalloc/test/unit/prof_tctx.c \
           gBolt/extern/jemalloc/test/unit/prof_thread_name.c \
           gBolt/extern/jemalloc/test/unit/ql.c \
           gBolt/extern/jemalloc/test/unit/qr.c \
           gBolt/extern/jemalloc/test/unit/rb.c \
           gBolt/extern/jemalloc/test/unit/retained.c \
           gBolt/extern/jemalloc/test/unit/rtree.c \
           gBolt/extern/jemalloc/test/unit/sc.c \
           gBolt/extern/jemalloc/test/unit/seq.c \
           gBolt/extern/jemalloc/test/unit/SFMT.c \
           gBolt/extern/jemalloc/test/unit/size_classes.c \
           gBolt/extern/jemalloc/test/unit/slab.c \
           gBolt/extern/jemalloc/test/unit/smoothstep.c \
           gBolt/extern/jemalloc/test/unit/spin.c \
           gBolt/extern/jemalloc/test/unit/stats.c \
           gBolt/extern/jemalloc/test/unit/stats_print.c \
           gBolt/extern/jemalloc/test/unit/test_hooks.c \
           gBolt/extern/jemalloc/test/unit/ticker.c \
           gBolt/extern/jemalloc/test/unit/tsd.c \
           gBolt/extern/jemalloc/test/unit/witness.c \
           gBolt/extern/jemalloc/test/unit/zero.c \
           gBolt/extern/jemalloc/test/integration/cpp/basic.cpp
TRANSLATIONS += gBolt/build/CMakeFiles/gbolt.dir/compiler_depend.ts

# Test case configuration
CONFIG(testcase) {
    TARGET = testlayoutwidget
    QT += testlib
    CONFIG += c++14 # Ensure C++14 for tests
    DEFINES += IS_TEST_BUILD

    # Define ONLY the sources needed for the test
    SOURCES = layoutwidget.cpp \
              testlayoutwidget.cpp \
              design_layout_viewer.cpp # Contains main()

    # Define ONLY the headers needed for the test
    HEADERS = layoutwidget.h

    # LIBS for test (usually same as app, unless specific test libs are needed)
    # Ensure gdstk, Clipper, Qhull, zlib are linked for tests too if LayoutWidget depends on them
    LIBS += /home/amrmuhammad/dev/gdstk/build/src/libgdstk.a \
            /home/amrmuhammad/dev/gdstk/build/external/libclipper.a \
            -L/usr/local/lib -lqhull_r \
            -lz
}

